### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/LocalBroadcastManager;

### ISSUE THREAD

**Issue by wastedabuser** [freshplanet/ANE-Facebook#201]
I got pretty much all the errors from all the other issues :( Somehow i managed to work around them. Currently i am stuck with this one:
```
E/AndroidRuntime(25721): java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/LocalBroadcastManager;
E/AndroidRuntime(25721):        at com.facebook.Session.postActiveSessionAction(Unknown Source)
E/AndroidRuntime(25721):        at com.facebook.Session.postStateChange(Unknown Source)
E/AndroidRuntime(25721):        at com.facebook.Session.open(Unknown Source)
E/AndroidRuntime(25721):        at com.facebook.Session.openForRead(Unknown Source)
E/AndroidRuntime(25721):        at com.freshplanet.ane.AirFacebook.LoginActivity.onCreate(Unknown Source)
E/AndroidRuntime(25721):        at android.app.Activity.performCreate(Activity.java:5933)
E/AndroidRuntime(25721):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
E/AndroidRuntime(25721):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
E/AndroidRuntime(25721):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
E/AndroidRuntime(25721):        at android.app.ActivityThread.access$800(ActivityThread.java:144)
E/AndroidRuntime(25721):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
E/AndroidRuntime(25721):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(25721):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(25721):        at android.app.ActivityThread.main(ActivityThread.java:5221)
E/AndroidRuntime(25721):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25721):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(25721):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/AndroidRuntime(25721):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
E/AndroidRuntime(25721): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.LocalBroadcastManager" on path: DexPathList[
[zip file "/data/app/air.air.Eldhelm-1/base.apk"],nativeLibraryDirectories=[/data/app/air.air.Eldhelm-1/lib/arm, /vendor/lib, /system/lib]]
E/AndroidRuntime(25721):        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(25721):        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime(25721):        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime(25721):        ... 18 more
E/AndroidRuntime(25721):        Suppressed: java.lang.ClassNotFoundException: android.support.v4.content.LocalBroadcastManager
E/AndroidRuntime(25721):                at java.lang.Class.classForName(Native Method)
E/AndroidRuntime(25721):                at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime(25721):                at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime(25721):                at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime(25721):                ... 19 more
E/AndroidRuntime(25721):        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

**Comment by wastedabuser** [comment]
So i managed work around the problem by recompiling the ANE with the android-support-v4.jar added as a dependency and including it in the package.
